### ISSUE TITLE
`Invalid boot.img, no ramdisk or kernel found` on OnePlus Ace2 Android 13

### ISSUE THREAD

**Issue by Byxs20** [capntrips/KernelFlasher#26]
Hi, I am also experiencing the problem of not being able to open the app, I have read what you need to solve this type of problem in your other issue so I am providing it to you first, I would be very thankful to you if you have the time to help me with this problem!

![image](https://github.com/capntrips/KernelFlasher/assets/64669718/3dd4cfb0-4f99-4c4b-9443-e52ceb469b69)

Added: I don't have `init_boot_a` and `init_boot_b` files.

[boot.zip](https://github.com/capntrips/KernelFlasher/files/14257645/boot.zip)

https://github.com/capntrips/KernelFlasher/releases/tag/v1.0.0-alpha019%2Ballow-non-ab

But I'm using this version just fine, but boot_b seems to have problems

![image](https://github.com/capntrips/KernelFlasher/assets/64669718/5647f5ae-b5a1-4a17-84fd-d76afc4734fb)

**Comment by capntrips** [comment]
The `v1.0.0-alpha019+allow-invalid` build was created specifically to address that issue (and those changes are included `v1.0.0-alpha019+allow-non-ab`). The error message in your first screenshot is expected behavior when the `boot` partition can't be unpacked.

As for the why, I'm guessing your inactive slot was empty. Copying the boot image to the inactive slot is certainly one way to eliminate the error, though I'm not sure what implications that might have if the bootloader unexpectedly changes slots.

I'm going to close this, as it appears to have worked as expected. If I'm overlooking something, feel free to reopen.
